name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Pac-Man graph
        uses: abozanona/pacman-contribution-graph@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_path: dist/pacman-contribution-graph.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
